### ISSUE TITLE
Running Codes on CPU?

### ISSUE THREAD

**Issue by frznkshn** [nvidia-riva/riva-asrlib-decoder#38]
Is there a simple way to run these codes on the CPU instead of the GPU?

**Comment by galv** [comment]
No, this doesn't support CPU. The purpose of this codebase is to enable a task that was traditionally run only on the CPU, beam search decoding, to run on the GPU. This is because state of the art workloads were at the point where 90% of the time was spent on CPU decoding, with the GPU active only 10% of the time. See figure 1 here: https://arxiv.org/abs/2311.04996

<img width="358" alt="image" src="https://github.com/nvidia-riva/riva-asrlib-decoder/assets/4767568/6a78aac4-acce-498a-9765-271a35509205">

We had several customers for whom using the GPU for inference was not economical because they used beam search, thus motivating moving beam search to the GPU.

Having said all of that, I suggest you look at pykaldi if you really want to try using CPU-based beam search decoders. I have not used it myself, however.
